name: test
on: [pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: pip_install
        env:
          FURY_AUTH: ${{ secrets.GEMFURY_PULL_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url=https://${FURY_AUTH}:@pypi.fury.io/johnbrussell/
      - name: run_tests
        run: |
          python3 -m unittest discover
